In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn import metrics

In [ ]:
car_dataset=pd.read_csv("/content/cars.csv")

In [ ]:
car_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [ ]:
car_dataset.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
car_dataset.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [ ]:
print(car_dataset.fuel.value_counts())

fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64

In [ ]:
print(car_dataset.transmission.value_counts())
print(car_dataset.seller_type.value_counts())

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64
seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [ ]:
car_dataset.replace({'fuel':{'Petrol':0,'Diesel':1,'CNG':2,'LPG':3,'Electric':4}},inplace=True)
car_dataset.replace({'seller_type':{'Dealer':0,'Individual':1,'Trustmark Dealer':2}},inplace=True)
car_dataset.replace({'transmission':{'Manual':0,'Automatic':1}},inplace=True)
car_dataset.replace({'owner':{'First Owner':0,'Second Owner':1,'Third Owner':2,'Fourth & Above Owner':3}},inplace=True)

In [ ]:
car_dataset.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,0,1,0,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,0,1,0,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,1,0,First Owner
3,Datsun RediGO T Option,2017,250000,46000,0,1,0,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,1,1,0,Second Owner

In [ ]:
X= car_dataset.drop(["name",'selling_price'],axis=1)
Y=car_dataset['selling_price']

In [ ]:
print(car_dataset)

                                     name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000
1                Maruti Wagon R LXI Minor  2007         135000      50000
2                    Hyundai Verna 1.6 SX  2012         600000     100000
3                  Datsun RediGO T Option  2017         250000      46000
4                   Honda Amaze VX i-DTEC  2014         450000     141000
...                                   ...   ...            ...        ...
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000
4337                  Maruti 800 AC BSIII  2009         110000      83000
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000
4339                     Renault KWID RXT  2016         225000      40000

     fuel seller_type  transmission         owner
0       0           1             0   First Owner
1       0           1             0   First Owner
2       1           1             0   First Owner
3       0           1             0   First Owner
4       1           1             0  Second Owner
...   ...         ...           ...           ...
4335    1           1             0  Second Owner
4336    1           1             0  Second Owner
4337    0           1             0  Second Owner
4338    1           1             0   First Owner
4339    0           1             0   First Owner

[4340 rows x 8 columns]

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=2)

now model training
1.Linear regression

In [ ]:
lin_reg_model=LinearRegression()

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Check if owner column in car_dataset still contains string values
# If so, re-apply the encoding and re-create X, Y, X_train, Y_train
if 'owner' in car_dataset.columns and car_dataset['owner'].dtype == 'object':
    print("Owner column still contains strings. Re-applying encoding and regenerating data splits...")
    car_dataset.replace({'owner':{'First Owner':0,'Second Owner':1,'Third Owner':2,'Fourth & Above Owner':3, 'Test Drive Car':4}},inplace=True)

    # Re-create X and Y from the updated car_dataset
    X = car_dataset.drop(["name",'selling_price'],axis=1)
    Y = car_dataset['selling_price']

    # Re-create X_train, X_test, Y_train, Y_test with the updated data
    X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1,random_state=2)

lin_reg_model.fit(X_train,Y_train)

LinearRegression()